# Q1: Streamlit app to query CSV using SQL via Groq LLM

import streamlit as st
import pandas as pd
from langchain_groq import ChatGroq
from pandasql import sqldf
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
GROQ_API_KEY = os.getenv("Groq_API")

# Streamlit app title
st.title("Ask CSV using SQL (Groq)")

# Initialize Groq LLM with a supported model
llm = ChatGroq(model="llama3-docchat-1.0-8b")

# Upload CSV
uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    # Show schema
    st.subheader("CSV Schema")
    st.write(df.dtypes)

    schema = "\n".join([f"{col} ({dtype})" for col, dtype in df.dtypes.items()])

    # Ask question
    question = st.text_input("Ask anything about this CSV:")

    if question:
        # Prompt LLM to generate SQL
        prompt = f"""
        Table Name: data
        Table Schema:
        {schema}

        Question: {question}

        Instructions:
        - Write ONLY a valid SQLite SELECT query
        - Use ONLY table name: data
        - Do NOT add explanation
        - Do NOT use markdown
        """
        try:
            result = llm.invoke(prompt)
            sql_query = result.content.strip()

            # Clean up code fences if present
            if sql_query.startswith("```"):
                sql_query = sql_query.replace("```sql", "").replace("```", "").strip()

            # Validate SQL
            if not sql_query.lower().startswith("select"):
                st.error("Invalid SQL generated by LLM")
                st.stop()

            # Display SQL
            st.subheader("Generated SQL")
            st.code(sql_query, language="sql")

            # Execute SQL on CSV data
            query_result = sqldf(sql_query, {"data": df})

            # Show query results
            st.subheader("Query Result")
            st.dataframe(query_result)

            # Ask LLM to explain result
            explanation_prompt = f"""
            Explain the following query result in simple English:

            {query_result.to_string(index=False)}
            """
            explanation = llm.invoke(explanation_prompt)

            st.subheader("Explanation")
            st.write(explanation.content.strip())

        except Exception as e:
            st.error(f"Error: {e}")
